name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: check chrome version
      run: google-chrome --version
      
    - name: install new version of chromedriver
      run: sudo apt-get install google-chrome-stable=85.0.4183.83-1
      
    - name: check chrome version2
      run: google-chrome --version  
#  
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 3.1.301
#    - name: Install dependencies
#      run: dotnet restore
#    - name: setup-chromedriver
#      uses: nanasess/setup-chromedriver@v1.0.1
#      with: 
#        chromedriver-version: '84.0.4147.30'
#    - name: Build
#      run: dotnet build --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
