name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      
    - name : check version chromedriver
      run : google-chrome --version
    - name : update chrome
      run : sudo apt-get upgrade google-chrome-stable -y
    - name : check version chromedriver
      run : google-chrome --version
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
